default: &default
  adapter: mysql2
  enconding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: localhost.dev

development:
  <<: *default
  username: root
  password: password
  host: localhost.dev
  database: mol_development

production:
  <<: *default
  username: root
  password: password
  host: localhost.dev
  database: mol_production

test:
  <<: *default
  username: root
  password: password
  host: localhost.dev
  database: mol_test